import { Lead, ActivityLog } from './types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

// ─── Real leads from Yoni Aloni's outreach sessions ───────────────────────

export const MOCK_LEADS: Lead[] = [

  // ── B-04 Outreach Queue (queued) ─────────────────────────────────────────
  // These have been scraped, researched, qualified, content created — ready to send

  {
    lead_id: 'ld-studio-iris',
    company_name: 'Studio Iris',
    website: 'https://agenticflow-pages.vercel.app/studio-iris/',
    industry: 'Photography Studio',
    employee_count: 2,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Eldad',
    contact_title: 'Owner',
    contact_email: 'studioiris@inter.net.il',
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 75,
    icp_notes: 'Photography studio, 40+ years experience. No Google reviews — clear automation gap. Instagram, Facebook, LinkedIn active. Lead response bot = strong fit.',
    rejection_reason: null,
    outreach_channel: 'email',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'Website shows copyright 2019. Zero Google reviews despite 40y experience — obvious pain point.',
    created_at: daysAgo(5), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-ran-cohen',
    company_name: 'Ran Cohen Photography',
    website: 'https://agenticflow-pages.vercel.app/ran-cohen/',
    industry: 'Photography',
    employee_count: 2,
    hq_location: 'Tel Aviv, Israel',
    linkedin_url: null,
    contact_name: 'Ran Cohen',
    contact_title: 'Photographer / Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 73,
    icp_notes: '355 Google reviews, 4.7 stars. YouTube, Instagram, Facebook, FAQ. No WhatsApp — leads from after-hours go unanswered. Booking automation = strong fit.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 052-4444160. No email found — outreach via WhatsApp only.',
    created_at: daysAgo(6), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-alex-art',
    company_name: 'Alex Art',
    website: 'https://agenticflow-pages.vercel.app/alex-art/',
    industry: 'Art Gallery / Photography',
    employee_count: 2,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Alex',
    contact_title: 'Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 68,
    icp_notes: 'Gallery + wedding photography. Active WhatsApp, Instagram, YouTube. No pricing, no quote automation. First-responder wins in photography market.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 052-2802386.',
    created_at: daysAgo(7), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-sharli-harri',
    company_name: 'Sharli Harri SH',
    website: 'https://agenticflow-pages.vercel.app/sharli-harri/',
    industry: 'Hair Salon',
    employee_count: 3,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Sharli',
    contact_title: 'Owner / Stylist',
    contact_email: 'info@sharli-harri.com',
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 76,
    icp_notes: 'Active Facebook with impressive work. No WhatsApp button, no online booking. High-volume salon — 24/7 appointment bot ideal. Email + WhatsApp available.',
    rejection_reason: null,
    outreach_channel: 'email',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 03-5758008. Email: info@sharli-harri.com.',
    created_at: daysAgo(4), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-nir-elias',
    company_name: 'Nir Elias Salon',
    website: 'https://agenticflow-pages.vercel.app/nir-elias/',
    industry: 'Hair Salon',
    employee_count: 4,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Nir Elias',
    contact_title: 'Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 70,
    icp_notes: 'Impressive product store with clear pricing. Dual revenue streams (salon + products) not cross-selling. No online appointment booking. Single bot can bridge both.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 050-2249151.',
    created_at: daysAgo(8), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-psagot-vet',
    company_name: 'Psagot Veterinary Center',
    website: 'https://agenticflow-pages.vercel.app/psagot-vet/',
    industry: 'Veterinary Clinic',
    employee_count: 8,
    hq_location: 'Psagot, Israel',
    linkedin_url: null,
    contact_name: 'Dr. Farhi',
    contact_title: 'Veterinarian / Owner',
    contact_email: 'vetpsagotclinic@gmail.com',
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 82,
    icp_notes: '4.9 stars Google. Active Instagram & Facebook. Annual subscription model. Emergency service offered. All appointments via manual WhatsApp — bottleneck at scale. Strong fit for 24/7 bot.',
    rejection_reason: null,
    outreach_channel: 'email',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 052-4562030. Email confirmed: vetpsagotclinic@gmail.com.',
    created_at: daysAgo(3), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-galit-vet',
    company_name: 'Galit Piner-Goldenberg Vet',
    website: 'https://agenticflow-pages.vercel.app/galit-vet/',
    industry: 'Veterinary Clinic (Holistic)',
    employee_count: 3,
    hq_location: 'Kfar Saba, Israel',
    linkedin_url: null,
    contact_name: 'Dr. Galit Piner-Goldenberg',
    contact_title: 'Veterinarian / Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-04', status: 'queued', assigned_agent: 'outbound-agent', created_by: 'qualification-agent',
    icp_score: 78,
    icp_notes: 'Holistic vet — acupuncture, homeopathy, chiropractic + cardiology & oncology collaboration. Rare niche in Israel. Almost no photos, no online booking, hours hard to find. High potential.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 054-9447080.',
    created_at: daysAgo(5), updated_at: daysAgo(1),
  },

  // ── B-05 Active Outreach (contacted) ─────────────────────────────────────

  {
    lead_id: 'ld-borochov',
    company_name: 'Borochov Hair Restoration',
    website: 'https://agenticflow-pages.vercel.app/borochov/',
    industry: 'Hair Restoration Salon',
    employee_count: 5,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Kobi / Vali',
    contact_title: 'Owners',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-05', status: 'contacted', assigned_agent: 'outbound-agent', created_by: 'outbound-agent',
    icp_score: 74,
    icp_notes: '9/10 rating, reviews highlight amazing hair restoration. Active WhatsApp and Instagram. No photo gallery on website — specialists with no visual proof. No evening bookings.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: daysAgo(7),
    first_message_text: 'היי קובי/ואלי 😊 שמי יוני, אני עוסק בבניית סוכני AI לעסקים. הכנתי לכם הדגמה אישית: https://agenticflow-pages.vercel.app/borochov/ וגם ניתוח מפורט: https://agenticflow-pages.vercel.app/borochov/report.html — 10 דקות שיחה ואני מראה לכם בדיוק מה זה יכול לתת לעסק שלכם.',
    followup_count: 0,
    next_followup_at: daysAgo(-3),
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 050-9707075. Sent WhatsApp day-7.',
    created_at: daysAgo(12), updated_at: daysAgo(7),
  },
  {
    lead_id: 'ld-ben-albageli',
    company_name: 'Ben Albageli Vet',
    website: 'https://agenticflow-pages.vercel.app/ben-albageli/',
    industry: 'Veterinary Clinic',
    employee_count: 4,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Ben Albageli',
    contact_title: 'Veterinarian / Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-05', status: 'contacted', assigned_agent: 'outbound-agent', created_by: 'outbound-agent',
    icp_score: 85,
    icp_notes: '5.0 stars Google. Personal relationship — Yoni is a client. Digital presence weak despite top rating. Evening bookings impossible. Strong trust baseline = high conversion potential.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: daysAgo(5),
    first_message_text: 'היי בן 😊 אני יוני — אני מביא אצלך את זואי וג\'ונם כבר תקופה. בזכות הטיפול שלך ב-5.0 כוכבים אני יודע שיש לך משהו ממש מיוחד. בניתי לך הדגמה אישית: https://agenticflow-pages.vercel.app/ben-albageli/ — 10 דקות שיחה ואני מראה לך הכל.',
    followup_count: 0,
    next_followup_at: daysAgo(-1),
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 03-9388824. Personal connection — Yoni is a client.',
    created_at: daysAgo(9), updated_at: daysAgo(5),
  },

  // ── B-06 Follow-up (following_up) ────────────────────────────────────────

  {
    lead_id: 'ld-inbar-vet',
    company_name: 'Inbar-Batser Vet Clinic',
    website: 'https://agenticflow-pages.vercel.app/inbar-vet/',
    industry: 'Veterinary Clinic',
    employee_count: 3,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Dr. Inbar-Batser',
    contact_title: 'Veterinarian / Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-06', status: 'following_up', assigned_agent: 'followup-agent', created_by: 'outbound-agent',
    icp_score: 80,
    icp_notes: '9.0 stars, 136 reviews. Treats rare animals (rabbits, parrots). No WhatsApp button on website, no online booking. Young growing practice — automation can scale intake.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: daysAgo(14),
    first_message_text: 'היי ד"ר ענבר 😊 9.0 מתוך 10 עם 136 ביקורות — זה אחד הציונים הגבוהים שראיתי. בניתי לכם הדגמה + ניתוח: https://agenticflow-pages.vercel.app/inbar-vet/ — 10 דקות שיחה: https://cal.com/yoniautomation/אוטומציה-עסקית',
    followup_count: 1,
    next_followup_at: daysAgo(0),
    response_received_at: null, response_sentiment: null,
    agent_notes: 'WhatsApp: 054-5401202. Follow-up #1 sent day 4.',
    created_at: daysAgo(18), updated_at: daysAgo(4),
  },

  // ── B-07 Responded ────────────────────────────────────────────────────────

  {
    lead_id: 'ld-sarfati-vet',
    company_name: 'Dr. Sarfati Vet Hospital',
    website: 'https://agenticflow-pages.vercel.app/sarfati-vet/',
    industry: 'Veterinary Hospital',
    employee_count: 12,
    hq_location: 'Israel',
    linkedin_url: null,
    contact_name: 'Dr. Sarfati',
    contact_title: 'Veterinarian / Owner',
    contact_email: null,
    contact_linkedin: null,
    current_board: 'B-07', status: 'responded', assigned_agent: null, created_by: 'outbound-agent',
    icp_score: 79,
    icp_notes: '260 reviews, 4.8 stars. Website in 5 languages (Hebrew, Russian, English, Italian, Hungarian). Client guides for download. No online booking despite high-end positioning.',
    rejection_reason: null,
    outreach_channel: 'whatsapp',
    first_message_sent_at: daysAgo(16),
    first_message_text: 'היי ד"ר צרפתי 😊 נכנסתי לאתר שלכם וממש הופתעתי לטובה — האתר זמין בחמש שפות, 260 ביקורות עם דירוג 4.8 כוכבים. בניתי לכם הדגמה: https://agenticflow-pages.vercel.app/sarfati-vet/',
    followup_count: 1,
    next_followup_at: null,
    response_received_at: daysAgo(3),
    response_sentiment: 'positive',
    agent_notes: 'Replied positively. WhatsApp: 054-4416277.',
    created_at: daysAgo(20), updated_at: daysAgo(3),
  },

  // ── Demo leads (B-01 / B-02) ─────────────────────────────────────────────

  {
    lead_id: 'ld-acme-tech',
    company_name: 'Acme Technologies',
    website: 'https://acme-tech.co.il',
    industry: 'SaaS',
    employee_count: 45,
    hq_location: 'Tel Aviv, Israel',
    linkedin_url: 'https://linkedin.com/company/acme-tech',
    contact_name: null, contact_title: null, contact_email: null, contact_linkedin: null,
    current_board: 'B-01', status: 'new', assigned_agent: 'research-agent', created_by: 'human',
    icp_score: null, icp_notes: null, rejection_reason: null,
    outreach_channel: null, first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null, agent_notes: null,
    created_at: daysAgo(1), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-greenfield',
    company_name: 'Greenfield Logistics',
    website: 'https://greenfield-log.com',
    industry: 'Logistics',
    employee_count: 120,
    hq_location: 'Haifa, Israel',
    linkedin_url: null,
    contact_name: null, contact_title: null, contact_email: null, contact_linkedin: null,
    current_board: 'B-01', status: 'in_progress', assigned_agent: 'research-agent', created_by: 'human',
    icp_score: null, icp_notes: null, rejection_reason: null,
    outreach_channel: null, first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null, agent_notes: 'Researching LinkedIn page.',
    created_at: daysAgo(2), updated_at: daysAgo(0),
  },
  {
    lead_id: 'ld-nova-ecom',
    company_name: 'Nova E-Commerce',
    website: 'https://nova-shop.co.il',
    industry: 'E-Commerce',
    employee_count: 30,
    hq_location: 'Tel Aviv, Israel',
    linkedin_url: 'https://linkedin.com/company/nova-ecom',
    contact_name: 'Tamar Ben-David', contact_title: 'CEO', contact_email: 'tamar@nova-shop.co.il',
    contact_linkedin: 'https://linkedin.com/in/tamar-bd',
    current_board: 'B-02', status: 'pending_review', assigned_agent: 'qualification-agent', created_by: 'research-agent',
    icp_score: null, icp_notes: null, rejection_reason: null,
    outreach_channel: null, first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null, agent_notes: null,
    created_at: daysAgo(3), updated_at: daysAgo(1),
  },
  {
    lead_id: 'ld-rockford',
    company_name: 'Rockford Manufacturing',
    website: 'https://rockford-mfg.com',
    industry: 'Manufacturing',
    employee_count: 500,
    hq_location: 'Chicago, USA',
    linkedin_url: null,
    contact_name: 'John Miller', contact_title: 'VP Operations', contact_email: null, contact_linkedin: null,
    current_board: 'B-08', status: 'archived', assigned_agent: null, created_by: 'qualification-agent',
    icp_score: 22, icp_notes: 'Wrong geography, wrong industry, too large.',
    rejection_reason: 'Outside target geography and industry. ICP score 22.',
    outreach_channel: null, first_message_sent_at: null, first_message_text: null,
    followup_count: 0, next_followup_at: null,
    response_received_at: null, response_sentiment: null, agent_notes: null,
    created_at: daysAgo(4), updated_at: daysAgo(1),
  },
]

export const MOCK_ACTIVITY: Record<string, ActivityLog[]> = {
  'ld-sarfati-vet': [
    { activity_id: 'act-s1', lead_id: 'ld-sarfati-vet', type: 'advance',   body: 'Researched: 260 reviews, 5 languages, no online booking. Advanced B-01→B-02.',         channel: null,      agent_id: 'research-agent',       created_at: daysAgo(19) },
    { activity_id: 'act-s2', lead_id: 'ld-sarfati-vet', type: 'advance',   body: 'ICP score 79 — qualified. Advanced B-02→B-04.',                                          channel: null,      agent_id: 'qualification-agent',   created_at: daysAgo(18) },
    { activity_id: 'act-s3', lead_id: 'ld-sarfati-vet', type: 'outreach',  body: 'First WhatsApp sent to Dr. Sarfati.',                                                     channel: 'whatsapp',agent_id: 'outbound-agent',        created_at: daysAgo(16) },
    { activity_id: 'act-s4', lead_id: 'ld-sarfati-vet', type: 'advance',   body: 'No reply after 3 days — moved to B-06 Follow-up.',                                        channel: null,      agent_id: 'outbound-agent',        created_at: daysAgo(13) },
    { activity_id: 'act-s5', lead_id: 'ld-sarfati-vet', type: 'followup',  body: 'Follow-up #1 sent.',                                                                      channel: 'whatsapp',agent_id: 'followup-agent',        created_at: daysAgo(8)  },
    { activity_id: 'act-s6', lead_id: 'ld-sarfati-vet', type: 'note',      body: 'Lead replied positively — moved to B-07. Human takeover.',                               channel: null,      agent_id: 'followup-agent',        created_at: daysAgo(3)  },
  ],
  'ld-inbar-vet': [
    { activity_id: 'act-i1', lead_id: 'ld-inbar-vet', type: 'advance',     body: 'Researched: 9.0/10, 136 reviews, treats rare animals. No WhatsApp on site.',             channel: null,      agent_id: 'research-agent',       created_at: daysAgo(17) },
    { activity_id: 'act-i2', lead_id: 'ld-inbar-vet', type: 'advance',     body: 'ICP score 80 — qualified. Advanced to outreach queue.',                                   channel: null,      agent_id: 'qualification-agent',   created_at: daysAgo(16) },
    { activity_id: 'act-i3', lead_id: 'ld-inbar-vet', type: 'outreach',    body: 'First WhatsApp sent to Dr. Inbar-Batser.',                                                channel: 'whatsapp',agent_id: 'outbound-agent',        created_at: daysAgo(14) },
    { activity_id: 'act-i4', lead_id: 'ld-inbar-vet', type: 'advance',     body: 'No reply after 3 days — moved to follow-up.',                                             channel: null,      agent_id: 'outbound-agent',        created_at: daysAgo(11) },
    { activity_id: 'act-i5', lead_id: 'ld-inbar-vet', type: 'followup',    body: 'Follow-up #1 sent. next_followup_at set to T+4d.',                                        channel: 'whatsapp',agent_id: 'followup-agent',        created_at: daysAgo(4)  },
  ],
  'ld-borochov': [
    { activity_id: 'act-b1', lead_id: 'ld-borochov', type: 'advance',      body: 'Researched: 9/10 rating, hair restoration specialist, no photo gallery online.',         channel: null,      agent_id: 'research-agent',       created_at: daysAgo(11) },
    { activity_id: 'act-b2', lead_id: 'ld-borochov', type: 'advance',      body: 'ICP score 74 — qualified.',                                                               channel: null,      agent_id: 'qualification-agent',   created_at: daysAgo(10) },
    { activity_id: 'act-b3', lead_id: 'ld-borochov', type: 'outreach',     body: 'First WhatsApp sent to Kobi/Vali.',                                                       channel: 'whatsapp',agent_id: 'outbound-agent',        created_at: daysAgo(7)  },
  ],
}

export function getMockLeadById(id: string): Lead | null {
  return MOCK_LEADS.find(l => l.lead_id === id) ?? null
}

export function getMockLeadsByBoard(boardId: string): Lead[] {
  return MOCK_LEADS.filter(l => l.current_board === boardId)
}
