import { Company, Content, Outreach, STATUS_TO_BOARD } from './types'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()

// SOP-001 nullable fields — shared default for legacy mock entries
const SOP_DEFAULTS: Pick<
  Company,
  'cowork_id' | 'website' | 'contact_name' | 'contact_email' | 'contact_phone' |
  'contact_linkedin' | 'cowork_raw_data' | 'scoring_result' | 'scoring_notes' | 'rejection_reason'
> = {
  cowork_id: null, website: null, contact_name: null, contact_email: null,
  contact_phone: null, contact_linkedin: null, cowork_raw_data: null,
  scoring_result: null, scoring_notes: null, rejection_reason: null,
}

// ─── Real leads from Yoni Aloni's outreach sessions ───────────────────────

export const ALL_MOCK_COMPANIES: (Company & {
  score_reasoning?: string
  email_address?: string | null
  page_url?: string | null
  email_subject?: string | null
  email_body?: string | null
})[] = [
  {
    ...SOP_DEFAULTS,
    id: 'lead-studio-iris',
    name: 'Studio Iris',
    domain: 'https://agenticflow-pages.vercel.app/studio-iris/',
    linkedin_url: null,
    industry: 'Photography Studio',
    size_estimate: '1–5',
    score: 1,
    status: 'potential',
    current_board: STATUS_TO_BOARD['potential'],
    source: 'google_maps',
    created_at: daysAgo(3),
    updated_at: daysAgo(3),
    notes: null,
    score_reasoning: 'Small creative studio with no online booking — high automation potential.',
    email_address: 'studioiris@inter.net.il',
    page_url: 'https://agenticflow-pages.vercel.app/studio-iris/',
    email_subject: 'הכנתי משהו עבור סטודיו איריס',
    email_body: 'שלום אלדד, בניתי לכם עמוד הדגמה שמראה בדיוק מה סוכן AI יכול לעשות לסטודיו שלכם.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-ran-cohen',
    name: 'Ran Cohen',
    domain: 'https://agenticflow-pages.vercel.app/ran-cohen/',
    linkedin_url: null,
    industry: 'Architecture',
    size_estimate: '1–5',
    score: 1,
    status: 'potential',
    current_board: STATUS_TO_BOARD['potential'],
    source: 'linkedin',
    created_at: daysAgo(4),
    updated_at: daysAgo(4),
    notes: null,
    score_reasoning: 'Freelance architect — lead qualification bot can save hours per week.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/ran-cohen/',
    email_subject: 'הכנתי משהו עבור ראן כהן',
    email_body: 'שלום ראן, הכנתי הדגמה של בוט שמגיב ללידים תוך שניות.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-alex-art',
    name: 'Alex Art',
    domain: 'https://agenticflow-pages.vercel.app/alex-art/',
    linkedin_url: null,
    industry: 'Art Gallery',
    size_estimate: '1–5',
    score: 2,
    status: 'potential',
    current_board: STATUS_TO_BOARD['potential'],
    source: 'google_maps',
    created_at: daysAgo(5),
    updated_at: daysAgo(5),
    notes: null,
    score_reasoning: 'Art gallery with active social — lead capture and quote automation ideal.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/alex-art/',
    email_subject: 'הכנתי משהו עבור אלכס ארט',
    email_body: 'שלום אלכס, בניתי הדגמה של סוכן AI שמטפל בלידים — כולל הצעות מחיר ראשוניות אוטומטיות.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-sharli-harri',
    name: 'Sharli Harri SH',
    domain: 'https://agenticflow-pages.vercel.app/sharli-harri/',
    linkedin_url: null,
    industry: 'Beauty & Wellness',
    size_estimate: '1–5',
    score: 1,
    status: 'potential',
    current_board: STATUS_TO_BOARD['potential'],
    source: 'google_maps',
    created_at: daysAgo(2),
    updated_at: daysAgo(2),
    notes: null,
    score_reasoning: 'Beauty salon with high booking volume — appointment bot can handle 24/7.',
    email_address: 'info@sharli-harri.com',
    page_url: 'https://agenticflow-pages.vercel.app/sharli-harri/',
    email_subject: 'שרלי הררי SH — בניתי לכם משהו',
    email_body: 'שלום שרלי, בניתי לכם הדגמה של סוכן AI שמקבל הזמנות תורים 24/7 — כולל בסופי שבוע.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-nir-elias',
    name: 'Nir Elias',
    domain: 'https://agenticflow-pages.vercel.app/nir-elias/',
    linkedin_url: null,
    industry: 'Business Services',
    size_estimate: '1–10',
    score: 2,
    status: 'potential',
    current_board: STATUS_TO_BOARD['potential'],
    source: 'linkedin',
    created_at: daysAgo(6),
    updated_at: daysAgo(6),
    notes: null,
    score_reasoning: 'Business consultant — AI bot for client intake and scheduling is a strong fit.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/nir-elias/',
    email_subject: 'ניר אליאס — בניתי לכם משהו',
    email_body: 'שלום ניר, הכנתי לכם דמו של בוט שמציג מחירים, מזמין תורים ומשיב ללקוחות — אוטומטית.',
  },
  // ─── Awaiting Approval ────────────────────────────────────────────────────
  {
    ...SOP_DEFAULTS,
    id: 'lead-psagot-vet',
    name: 'Psagot Vet Clinic',
    domain: 'https://agenticflow-pages.vercel.app/psagot-vet/',
    linkedin_url: null,
    industry: 'Veterinary',
    size_estimate: '5–15',
    score: 2,
    status: 'awaiting_approval',
    current_board: STATUS_TO_BOARD['awaiting_approval'],
    source: 'google_maps',
    created_at: daysAgo(2),
    updated_at: daysAgo(1),
    notes: null,
    score_reasoning: 'High-volume vet clinic, busy reception — emergency WhatsApp bot ideal.',
    email_address: 'vetpsagotclinic@gmail.com',
    page_url: 'https://agenticflow-pages.vercel.app/psagot-vet/',
    email_subject: 'הכנתי הדגמה לקליניקת מרכז וטרינרי פסגות',
    email_body: 'שלום ד"ר פרחי, הכנתי לכם הדגמה + דוח מלא על איך בוט WhatsApp יכול לקלוט פניות חירום ולקבוע תורים 24/7.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-galit-vet',
    name: 'Galit Vet Clinic',
    domain: 'https://agenticflow-pages.vercel.app/galit-vet/',
    linkedin_url: null,
    industry: 'Veterinary',
    size_estimate: '1–5',
    score: 1,
    status: 'awaiting_approval',
    current_board: STATUS_TO_BOARD['awaiting_approval'],
    source: 'google_maps',
    created_at: daysAgo(3),
    updated_at: daysAgo(2),
    notes: null,
    score_reasoning: 'Small dedicated vet — appointment scheduling bot saves 2-3h/day.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/galit-vet/',
    email_subject: 'הכנתי הדגמה לקליניקת גלית פינר-גולדנברג',
    email_body: 'שלום גלית, הכנתי הדגמה אישית + ניתוח של מה אוטומציה יכולה לחסוך בקליניקה שלכם.',
  },
  // ─── Sent / Outreach ──────────────────────────────────────────────────────
  {
    ...SOP_DEFAULTS,
    id: 'lead-sarfati-vet',
    name: 'Dr. Sarfati Vet',
    domain: 'https://agenticflow-pages.vercel.app/sarfati-vet/',
    linkedin_url: null,
    industry: 'Veterinary',
    size_estimate: '5–15',
    score: 2,
    status: 'replied',
    current_board: STATUS_TO_BOARD['replied'],
    source: 'google_maps',
    created_at: daysAgo(10),
    updated_at: daysAgo(2),
    notes: null,
    score_reasoning: 'Active clinic with WhatsApp group — AI triage agent is a strong fit.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/sarfati-vet/',
    email_subject: 'הכנתי הדגמה לקליניקת ד"ר אבי שרפתי',
    email_body: 'שלום ד"ר שרפתי, בניתי הדגמה + דוח על חיסכון בשעות עבודה עם סוכן AI לוטרינריה.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-inbar-vet',
    name: 'Inbar Vet Clinic',
    domain: 'https://agenticflow-pages.vercel.app/inbar-vet/',
    linkedin_url: null,
    industry: 'Veterinary',
    size_estimate: '1–5',
    score: 1,
    status: 'followup_sent',
    current_board: STATUS_TO_BOARD['followup_sent'],
    source: 'google_maps',
    created_at: daysAgo(12),
    updated_at: daysAgo(3),
    notes: null,
    score_reasoning: 'Young practice growing fast — automation can scale intake without extra staff.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/inbar-vet/',
    email_subject: 'הכנתי הדגמה לקליניקת ד"ר ינבר-בצר',
    email_body: 'שלום ד"ר ינבר-בצר, בניתי הדגמה + דוח מותאם לקליניקה שלכם.',
  },
  {
    ...SOP_DEFAULTS,
    id: 'lead-borochov',
    name: 'Borochov Vet',
    domain: 'https://agenticflow-pages.vercel.app/borochov/',
    linkedin_url: null,
    industry: 'Veterinary',
    size_estimate: '5–15',
    score: 2,
    status: 'sent',
    current_board: STATUS_TO_BOARD['sent'],
    source: 'google_maps',
    created_at: daysAgo(7),
    updated_at: daysAgo(1),
    notes: null,
    score_reasoning: 'Established clinic with busy phone lines — booking automation is clear win.',
    email_address: null,
    page_url: 'https://agenticflow-pages.vercel.app/borochov/',
    email_subject: 'בורוכוב — בניתי לכם משהו',
    email_body: 'שלום צוות בורוכוב, הכנתי לכם הדגמה אישית של מה שאפשר לחסוך בעבודה ידנית.',
  },
]

// ─── Board-specific views ─────────────────────────────────────────────────

// New Content defaults for mock data
const mockContent = (c: (typeof ALL_MOCK_COMPANIES)[0]): Content => ({
  id: `content-${c.id}`,
  company_id: c.id,
  company_slug: c.id.replace('lead-', ''),
  page_url: c.page_url ?? null,
  page_status: 'deployed',
  landing_page_failed: false,
  report_url: null,
  report_content: null,
  report_status: 'ready',
  email_subject: c.email_subject ?? null,
  email_subtitle: null,
  email_body: c.email_body ?? null,
  email_links: {},
  followup_subject: null,
  followup_body: null,
  created_at: c.updated_at,
})

export const MOCK_CHAMPIONS = ALL_MOCK_COMPANIES.filter(c => c.status === 'potential')

export const MOCK_APPROVAL = ALL_MOCK_COMPANIES
  .filter(c => c.status === 'awaiting_approval' || c.status === 'awaiting_followup_approval')
  .map(c => ({ ...c, content: mockContent(c) }))

export const MOCK_OUTREACH = ALL_MOCK_COMPANIES
  .filter(c => ['sent', 'replied', 'followup_sent'].includes(c.status))
  .map((c, i) => ({
    ...c,
    outreach: {
      id: `outreach-${c.id}`,
      company_id: c.id,
      content_id: `content-${c.id}`,
      recipient_email: c.email_address ?? `contact@${c.id}.co.il`,
      gmail_message_id: `msg_${c.id}`,
      gmail_thread_id: `thread_${c.id}`,
      sent_at: daysAgo(7 - i),
      replied: c.status === 'replied',
      replied_at: c.status === 'replied' ? daysAgo(3 - i) : null,
      reply_preview: c.status === 'replied' ? 'נשמע מעניין, נשמח לשמוע עוד!' : null,
      reply_body: c.status === 'replied' ? 'נשמע מעניין, נשמח לשמוע עוד!' : null,
      follow_up_count: c.status === 'followup_sent' ? 1 : 0,
      last_follow_up_at: c.status === 'followup_sent' ? daysAgo(2) : null,
    } as Outreach,
  }))

export function getMockCompanyById(id: string) {
  return ALL_MOCK_COMPANIES.find(c => c.id === id) ?? null
}
